* Pretty-printer for a Coq project's dependency graph

This script pretty-prints the dependency graph generated by ~coqdep(1)~ by transforming the output of ~coqdep~ into a graph description in the ~dot~ format, producing a pdf file.

** Requirements

- ~coqdep(1)~ is required (shipped with Coq),
- ~tred(1)~,  ~gvpr(1)~, and ~dot(1)~, from the ~graphviz~ project do the heavy lifting,
- ~find(1)~ is required if the ~_CoqProject~ does *not* list the ~.v~ files.

** Usage

Compile your project, then put the ~coqdepgraph.py~ script into your ~$PATH~ and call it from the root of a Coq project, next to where the ~_CoqProject~ resides. Currently, no command line argument parsing is implemented, but ~coqdepgraph.py foo.bar "baz.*"test~ will use the first argument as regexp to include modules and the second argument as regexp to exclude modules. The name of the pdf output will be ~deps-foo.bar.pdf~, where ~foo.bar~ is the longest shared prefix of all included modules. Including this prefix in the name allows producing different visualisations for different subfolders of a project.

** Related projects

- https://github.com/coq-community/coq-dpdgraph is a Coq plugin which provides fine-grained insights about dependencies between individual Coq-objects
